# Result Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: results-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: results
  template:
    metadata:
      labels:
        app: results
    spec:
      containers:
      - name: result-container
        
        image: bacon21/result
        ports:
          - containerPort: 80
        env:
          - name: POSTGRES_HOST
            value: "postgres-service"  
          - name: POSTGRES_PORT
            value: "5432"
---
# Result Service
apiVersion: v1
kind: Service
metadata:
  name: results-service
spec:
  selector:
    app: results
  ports:
    - port: 80
      targetPort: 80
