apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: SXJvbmhhY2tQb3N0Z3JlcyE=
  REDIS_PASSWORD: SXJvbmhhY2tSZWRpcyE=
