
# Postgres Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
          - containerPort: 5432
        env:
          - name: DB_HOST
            value: "postgres-service"
          - name: DB_USERNAME
            value: "postgres"
          - name: DB_PASSWORD 
            value: "postgres"
          - name: DB_NAME
            value: "postgres"
          - name: REDIS_HOST
            value: "redis-service"
---
# Postgres Service
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - name: postgres-port
      port: 5432
      targetPort: 5432
