---
# Vote Deployment Template
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-chart.fullname" . }}-vote  # Combines release name with suffix; adjust if needed
spec:
  replicas: {{ .Values.vote.replicaCount }}        # Set the replica count for vote in values.yaml
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - name: vote-container
        image: "{{ .Values.vote.image.repository }}:{{ .Values.vote.image.tag }}"  # Image details from values.yaml
        ports:
          - containerPort: 80
        env:
          - name: REDIS_HOST
            value: {{ .Values.vote.env.redisHost | quote }}  # Set the Redis host (e.g., "redis-service")
          - name: REDIS_PORT
            value: {{ .Values.vote.env.redisPort | quote }}  # Set the Redis port (e.g., "6379")
---
# Vote Service Template
apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-chart.fullname" . }}-vote-service  # Combined name for the service
spec:
  selector:
    app: vote
  type: LoadBalancer  # Use LoadBalancer or adjust if using a different service type
  ports:
    - port: 80
      targetPort: 80
